---
editor_options: 
  markdown: 
    wrap: 72
---

```{r}
library(daltoolbox)
library(readr)
library(lubridate)
library(dplyr)
library(ggplot2)
library(zoo)
library(tspredit)

source('./util.R')
```

## Carregar csv

```{r}
filename <- "autuacao_mensal_filtrada.csv"
df <- read.csv(filename) 

if (nrow(df) == 0) {
  stop("O data.frame 'df' está vazio. Não é possível prosseguir.")
}

```

## Config

```{r}
test_size <- 12
sw_size <- 36

model_config <- ts_mlp(ts_norm_gminmax(), input_size=sw_size, size=1, decay=0.1, maxit=10) 
```

## Treinamento e Teste

```{r}
results <- data.frame()

for(sw in sw_size){
  x <- df$valor_pago
  ts <- ts_data(x, sw)
  
  samp <- ts_sample(ts, test_size = test_size)
  
  io_train <- ts_projection(samp$train)
  io_test <- ts_projection(samp$test)

  model <- ts_mlp(ts_norm_gminmax(), input_size=sw, size=1, decay=0.1, maxit=1000)
  model <- fit(model, x=io_train$input, y=io_train$output)
  
  adjust <- predict(model, io_train$input)
  prediction <- predict(model, x=io_test$input[1, ], steps_ahead=test_size)
  
  ev_test <- evaluate(model, as.vector(io_test$output), as.vector(prediction))
  
  ev_df <- data.frame(
    sw_size = sw,
    mse = ev_test$mse,
    smape = ev_test$smape,
    r2 = ev_test$R2
  )
  
  yvalues <- c(as.vector(io_train$output), as.vector(io_test$output))
  plot_obj <- plot_ts_pred(y=yvalues,
                           yadj=as.vector(adjust),
                           ypre=as.vector(prediction)) + theme(text = element_text(size=16))
  
  create_directories("mlp_janelas_crescentes")
  
  plot_name <- paste("janela_", sw, "_plot")
  salvar_plot(plot_obj, "plots_janelas_crescentes", plot_name)

  results <- rbind(results, ev_df)
}

results
View(results)
```

```{r}
View(results)
```
