#Dependências

```{r}
library(daltoolbox)
library(readr)
library(lubridate)
library(dplyr)
library(ggplot2)
```

#Cabeçalho

```{r}
head(df_receita_por_mes)
```

```{r}
arrecadacao_por_mes <- data.frame(df_receita_por_mes)
```

```{r}
head(arrecadacao_por_mes)
```

# Valor pago pelo dia da autuação

```{r}
ggplot(arrecadacao_por_mes, aes(x = data, y = valor_arrecadacao)) +
  geom_line() +
  labs(
    title = "Arecadação por mês",
    x = "Data",
    y = "Valor arrecadado"
  ) +
  theme_minimal() # Opcional: um tema minimalista para o gráfico
```

# Série temporal arrecadação mensal com frequência 12

```{r}
ts_arrecadacao_mensal <- ts(arrecadacao_por_mes$valor_arrecadacao, frequency=12)
```

# Decomposição da arrecadação mensal

```{r}
library(ggplot2)
library(dplyr)
library(forecast)

# Supondo que seu DataFrame 'arrecadacao_por_mes' tenha colunas 'ano', 'mes' e 'valor_arrecadacao'

# Criar a série temporal
ts_arrecadacao_mensal <- ts(arrecadacao_por_mes$valor_arrecadacao, frequency = 12, start = c(min(arrecadacao_por_mes$ano), min(arrecadacao_por_mes$mes)))

# Decompor a série temporal usando stl
decomposicao_arrecadacao_mensal_stl <- stl(ts_arrecadacao_mensal, s.window = "periodic")
componentes_stl <- as.data.frame(decomposicao_arrecadacao_mensal_stl$time.series)

# Criar um DataFrame para os componentes da decomposição
df_plot_componentes <- componentes_stl %>%
  mutate(
    time = time(ts_arrecadacao_mensal),
    ano = floor(time),
    mes_num = cycle(time),
    mes_ano = format(as.Date(paste(ano, mes_num, 1, sep = "-")), "%b-%Y")
  ) %>%
  pivot_longer(cols = c("seasonal", "trend", "remainder"), names_to = "componente", values_to = "valor")

# Criar um DataFrame para a série original
df_original <- arrecadacao_por_mes %>%
  mutate(
    time = time(ts_arrecadacao_mensal),
    ano = floor(time),
    mes_num = cycle(time),
    mes_ano = format(as.Date(paste(ano, mes_num, 1, sep = "-")), "%b-%Y"),
    componente = "data",
    valor = valor_arrecadacao
  ) %>%
  select(time, ano, mes_num, mes_ano, componente, valor)

# Combinar os DataFrames
df_plot <- rbind(df_plot_componentes, df_original)

# Plotar os componentes com ggplot2
ggplot(df_plot, aes(x = time, y = valor)) +
  geom_line() +
  facet_wrap(~ componente, scales = "free_y", ncol = 1) +
  scale_x_continuous(breaks = time(ts_arrecadacao_mensal)[seq(1, length(ts_arrecadacao_mensal), by = 12)],
                     labels = unique(df_plot$mes_ano)[seq(1, length(unique(df_plot$mes_ano)), by = 12)]) +
  labs(title = "Decomposição da Arrecadação Mensal",
       x = "Mês-Ano",
       y = "Valor") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
